#AI Lab 09
K213309 | BCS-6F

##Installing Dependencies

In [ ]:
!pip install gym

##Task 1

In [ ]:
'''Implement Q-learning algorithm using OpenAI gym environment.'''

import numpy as np
import gym
import random

env = gym.make("FrozenLake-v1")
action_size = env.action_space.n
state_size = env.observation_space.n
qtable = np.zeros((state_size, action_size))

total_episodes = 20000
learning_rate = 0.7
max_steps = 99
gamma = 0.7
epsilon = 1.0
max_epsilon = 1.0
min_epsilon = 0.01
decay_rate = 0.5

rewards = []

for episode in range(total_episodes):
    state = env.reset()
    step = 0
    done = False
    total_rewards = 0

    for step in range(max_steps):
        exp_exp_tradeoff = random.uniform(0, 1)
        if exp_exp_tradeoff > epsilon:
            action = np.argmax(qtable[state,:])
        else:
            action = env.action_space.sample()
        new_state, reward, done, info = env.step(action)
        qtable[state, action] = qtable[state, action] + learning_rate * (reward + gamma * np.max(qtable[new_state, :]) - qtable[state, action])
        total_rewards += reward
        state = new_state
        if done == True:
            break
    epsilon = min_epsilon + (max_epsilon - min_epsilon)*np.exp(-decay_rate*episode)
    rewards.append(total_rewards)


print ("Score over time: " +  str(sum(rewards)/total_episodes))
print(qtable)

Score over time: 0.0
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##Task 2

In [ ]:
'''The Smart cab's job is to pick up the passenger at one location and drop them off in another.
The agent should receive a high positive reward for a successful drop off because this
behavior is highly desired
The agent should be penalized if it tries to drop off a passenger in wrong locations
The agent should get a slight negative reward for not making it to the destination after
every time-step.
The passenger can be in one of the four possible locations: R, G, Y, B, which are
represented in row, column coordinates as (0,0), (0,4), (4,0), (4,3) respectively.
Additionally, we need to consider a fifth state where the passenger is already inside the
taxi. Therefore, the number of possible states for the passenger's location is 5.
The destination can be one of the four possible locations: R, G, Y, B, which are also
represented in row, column coordinates. Therefore, the number of possible states for the
destination is 4.
We have six possible actions:
1. south
2. north
3. east
4. west
5. pickup
6. drop off
Implement the above problem using Gym environment called Taxi-V2.'''

import gym
import numpy as np
import random
from IPython.display import clear_output

env = gym.make("Taxi-v3").env
env.reset()
env.render()

print('Number of states:{}'.format(env.observation_space.n))
print('Number of actions:{}'.format(env.action_space.n))


alpha = 0.1
gamma = 0.6
epsilon = 0.1
q_table = np.zeros([env.observation_space.n, env.action_space.n])

num_of_episodes = 100000
for episode in range(0 ,num_of_episodes):
    # reset the environment
    state = env.reset()

    # Initialized the variables
    reward = 0
    terminated = False
    # if we want to not terminale the loop
    while not terminated:
        # Take learned path or explore new actions based on the epsilon
        if random.uniform(0,1)<epsilon:
            action = env.action_space.sample()
        else:
            action = np.argmax(q_table[state])
            # Take action
            next_state, reward, terminated, info = env.step(action)


            # Recalculate
            q_value = q_table[state , action]
            max_value = np.max(q_table[next_state])
            new_q_value = (1-alpha)* q_value + alpha * (reward + gamma * max_value)


            # update q_table
            q_table[state , action] = new_q_value
            state = next_state
    if (episode + 1)%100 == 0:
                clear_output(wait = True)
                print('Episode: {}'.format(episode + 1))
                env.render()





print('*****************************************')
print('Training is done!\n')
print('*****************************************')

Episode: 100000
*****************************************
Training is done!

*****************************************


##Task 3

In [ ]:
'''A well equipped state of the art hospital monitors data of the patients using AI devices
remotely. Each patient has different sensors deployed on his/her body to acquire the values
of sugar, Blood Pressure etc. Day and night expelling of the data requires infinite lifetime
which is the ideal situation and nearly impossible due to DC devices deployment but to
increase its lifetime we can go for certain AI techniques e.g reinforcement learning by
measuring its nearest path to the sink from the cluster head. Develop such algorithm to
increase the network lifetime upto maximum extent using Reinforcement learning. Your
code must contain the cost factor while calculating the reward function for the next state.'''